// Generated by CoffeeScript 1.8.0
(function() {
  var DateParser;

  DateParser = module.exports = {
    LOCALES: {
      'zh-TW': require("./lib/zh-TW")
    },
    DEFAULT_LOCALE: 'zh-TW',
    locale: function(locale) {
      if (this.LOCALES[locale]) {
        return this.DEFAULT_LOCALE = locale;
      } else {
        return console.error("No such locale: " + locale);
      }
    },
    parse: function(text, locale) {
      var error, expression, expressions, result, _i, _len, _ref, _ref1;
      if (!text) {
        text = '';
      }
      if (!locale) {
        locale = this.DEFAULT_LOCALE;
      }
      expressions = (_ref = this.LOCALES[locale]) != null ? _ref.expressions : void 0;
      if (!expressions) {
        console.error("No such locale: " + locale);
        return null;
      }
      _ref1 = this.LOCALES[locale].expressions;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        expression = _ref1[_i];
        try {
          result = expression(text);
          if (result) {
            return result;
          }
        } catch (_error) {
          error = _error;
          console.error('error', error);
        }
      }
      return null;
    },
    number2integer: function(text, locale) {
      var _ref;
      if (!text) {
        text = '';
      }
      if (!locale) {
        locale = this.DEFAULT_LOCALE;
      }
      return (_ref = this.LOCALES[locale]) != null ? typeof _ref.number2integer === "function" ? _ref.number2integer(text) : void 0 : void 0;
    },
    time2object: function(text, locale) {
      var _ref;
      if (!text) {
        text = '';
      }
      if (!locale) {
        locale = this.DEFAULT_LOCALE;
      }
      return (_ref = this.LOCALES[locale]) != null ? typeof _ref.time2object === "function" ? _ref.time2object(text) : void 0 : void 0;
    },
    dayTime2date: function(text, locale) {
      var _ref;
      if (!text) {
        text = '';
      }
      if (!locale) {
        locale = this.DEFAULT_LOCALE;
      }
      return (_ref = this.LOCALES[locale]) != null ? typeof _ref.dayTime2date === "function" ? _ref.dayTime2date(text) : void 0 : void 0;
    },
    date2object: function(text, locale) {
      var _ref;
      if (!text) {
        text = '';
      }
      if (!locale) {
        locale = this.DEFAULT_LOCALE;
      }
      return (_ref = this.LOCALES[locale]) != null ? typeof _ref.date2object === "function" ? _ref.date2object(text) : void 0 : void 0;
    },
    dateExpression2date: function(text, locale) {
      var _ref;
      if (!text) {
        text = '';
      }
      if (!locale) {
        locale = this.DEFAULT_LOCALE;
      }
      return (_ref = this.LOCALES[locale]) != null ? typeof _ref.dateExpression2date === "function" ? _ref.dateExpression2date(text) : void 0 : void 0;
    }
  };

}).call(this);
